$background = 121316
$onBackground = e3e2e6
$surface = 121316
$surfaceDim = 121316
$surfaceBright = 38393c
$surfaceContainerLowest = 0d0e11
$surfaceContainerLow = 1a1b1e
$surfaceContainer = 1f1f23
$surfaceContainerHigh = 292a2d
$surfaceContainerHighest = 343538
$onSurface = e3e2e6
$surfaceVariant = 44474e
$onSurfaceVariant = c4c6d0
$outline = 8e9099
$outlineVariant = 44474e
$inverseSurface = e3e2e6
$inverseOnSurface = 2f3033
$shadow = 000000
$scrim = 000000
$surfaceTint = afc7f8
$primary = afc7f8
$primaryDim = b4ccfe
$onPrimary = 153058
$primaryContainer = 88a0cf
$onPrimaryContainer = 1d365f
$inversePrimary = 475f8a
$primaryFixed = d7e3ff
$primaryFixedDim = afc7f8
$onPrimaryFixed = 001b3f
$onPrimaryFixedVariant = 2e4770
$secondary = bec6dc
$secondaryDim = dae2f9
$onSecondary = 283141
$secondaryContainer = 3e4759
$onSecondaryContainer = adb5ca
$secondaryFixed = dae2f9
$secondaryFixedDim = bec6dc
$onSecondaryFixed = 131c2b
$onSecondaryFixedVariant = 3e4759
$tertiary = e9c178
$tertiaryDim = f8cf84
$onTertiary = 412d00
$tertiaryContainer = bf9a55
$onTertiaryContainer = 493300
$tertiaryFixed = ffdea6
$tertiaryFixedDim = e9c178
$onTertiaryFixed = 271900
$onTertiaryFixedVariant = 5d4202
$error = ffb4ab
$errorDim = ff554a
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryPaletteKeyColor = 5f77a4
$secondaryPaletteKeyColor = 6e778a
$tertiaryPaletteKeyColor = bf9a55
$neutralPaletteKeyColor = 77777b
$neutralVariantPaletteKeyColor = 74777f
$errorPaletteKeyColor = de3730
$primary_paletteKeyColor = 5f77a4
$secondary_paletteKeyColor = 6e778a
$tertiary_paletteKeyColor = bf9a55
$neutral_paletteKeyColor = 77777b
$neutral_variant_paletteKeyColor = 74777f
$term0 = 353434
$term1 = 8881ff
$term2 = 44def5
$term3 = ffdcf2
$term4 = 8cadd4
$term5 = 9ea5ef
$term6 = 95d0fb
$term7 = e8d3de
$term8 = ac9fa9
$term9 = a39eff
$term10 = 89ecff
$term11 = c9fff3
$term12 = aec3da
$term13 = b7baf8
$term14 = b8e0ff
$term15 = ffffff
$rosewater = f4f0fa
$flamingo = e2dff5
$pink = d7dbff
$mauve = abbeff
$red = a9adff
$maroon = b9baf1
$peach = e0c2f9
$yellow = d0f9f4
$green = c3e4ff
$teal = c8e2ff
$sky = c4ddff
$sapphire = a4caff
$blue = 9abdff
$lavender = b7ccff
$klink = 5788ce
$klinkSelection = 5689ce
$kvisited = 607add
$kvisitedSelection = 5f7bdd
$knegative = 7977ff
$knegativeSelection = 7878ff
$kneutral = c794ff
$kneutralSelection = c794ff
$kpositive = 1ab3ff
$kpositiveSelection = 0eb3ff
$text = e3e2e6
$subtext1 = c4c6d0
$subtext0 = 8e9099
$overlay2 = 7c7d85
$overlay1 = 696a71
$overlay0 = 57595f
$surface2 = 46484d
$surface1 = 36373c
$surface0 = 242529
$base = 121316
$mantle = 121316
$crust = 111215
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
