#### Hyprland Config ####
#
# :D :D :D made by pgp :D :D :D
$terminal = kitty
$fileManager = dolphin
$browser = firefox
$libre = librewolf


source =  ~/.config/hypr/configs/rounding.conf
source = ~/.config/hypr/configs/blur.conf
source = ~/.config/hypr/configs/exec.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/shadows.conf
source = ~/.config/hypr/configs/input.conf
source = ~/.config/hypr/configs/misc.conf
source = ~/.config/hypr/configs/gestures.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/general.conf
source = ~/.config/hypr/hyprglass.conf

misc {
    disable_splash_rendering = true
  }

# OVERRIDES
source = ~/.local/share/ambxst/hyprland.conf
source = ~/.config/hypr/configs/exec.conf
