plugin:hyprglass {
    default_theme = dark
    default_preset = light

    tint_color = 0x8899aa22

    brightness = 0.1
    blur_strength = 10
    dark:brightness = 0.82
    light:adaptive_boost = 0.5
    refraction_strength = 20
    fresnel_strength = 0.6
    blur_iterations = 3


    preset = name:clear, glass_opacity:0.5, blur_strength:50, refraction_strength:0.6, fresnel_strength:0.6, specular_strength:2, adaptive_dim:0.4, lens_distortion:1, vibrancy:0.15, adaptive_boost:0.4, blur_iterations:3, chromatic_aberration:0.5 
    preset = name:clear:dark, brightness:0.7, glass_opacity:0.3
    preset = name:clear:light, brightness:1.2
    preset = name:light, brightness:1.00, blur_strength:0.1, refraction_strength:16, blur_iterations:5, fresnel_strength:0.90, specular_strength:0.5, adaptive_boost:0.01, adaptive_dim:0.0, vibrancy:1, glass_opacity:1, edge_thickness:0.04, lens_distortion:0.60, contrast:0.84, saturation: 0.87, vibrancy_darkness:1.40


    preset = name:contrasted, inherits:high_contrast, contrast:1.2, adaptive_dim:1.5
    preset = name:contrasted:dark, tint_color:0x02142aa9

    layers {
        enabled = 1
        manage_window_blur = 1
        namespaces = waybar, swaync, quickshell:bezel, kitty
        exclude_namespaces = debug-panel
        preset = clear
        namespace_presets = quickshell:bezel:ui
        namespace_mask_thresholds = waybar:bezel=0.10, quickshell:bezel=0.3
    }
}
