preload = ~/Pictures/Wallpapers/wallhaven-w5xdzx.jpg
preload = ~/Pictures/Wallpapers/wallhaven-w5xdzx.jpg

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/Wallpapers/wallhaven-w5xdzx.jpg
}

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Wallpapers/wallhaven-w5xdzx.jpg
}
splash = false
