general {
    layout=dwindle

    gaps_in=3
    gaps_out=10
    border_size=3

    col.active_border= rgba(EAE8FFee) #d0001e6 -50deg rgba(00ADB7ee) 50deg # 3028B6
    col.inactive_border= rgba(ADACB5ee) -50deg rgba(ff0000ee) 50deg


    resize_on_border = true

    allow_tearing = false

}

