decoration {
    rounding = 5
    rounding_power = 10
    active_opacity = 1
    inactive_opacity = 0.8
    dim_inactive = true
    dim_strength = 0.0
    dim_special = 0.0
    dim_around = 0
    fullscreen_opacity = 1.00
    border_part_of_window = true
  }
