decoration {
    shadow {
        enabled = true
        range = 1
        render_power = 5
        color = rgba(2D2142ee)
        color_inactive = rgba(343FA3dd)
        sharp = false
        scale = 1.0
        offset = 0, 0
      }
  }

  # this shit sucks i need a plugin
